# Generated by Django 5.0.7 on 2024-07-30 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_page', '0005_delete_userdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('daftar_name', models.CharField(max_length=255)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.IntegerField(blank=True, null=True)),
                ('creating_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_page.userprofile')),
            ],
            options={
                'db_table': 'daftar',
            },
        ),
    ]
