# Generated by Django 5.0.7 on 2024-07-30 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='video',
            table='daftar_data',
        ),
    ]
