# Generated by Django 5.0.7 on 2024-07-30 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='video',
            table='daftar',
        ),
    ]
