# Generated by Django 5.0.7 on 2024-07-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_daftar_createpitch_pitchvideo_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaftarDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('daftar_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('sector', models.CharField()),
                ('stage', models.CharField()),
                ('demolink', models.TextField()),
                ('problem_loacation', models.CharField()),
                ('solving_your_problem', models.BooleanField()),
                ('last_updated_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.BigIntegerField(blank=True, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daftar_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PitchVideos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pitch_id', models.BigIntegerField()),
                ('question_id', models.BigIntegerField()),
                ('question_language', models.CharField()),
                ('question_url', models.TextField()),
                ('last_updated_date', models.DateField(blank=True, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pitch_videos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfilePageUserprofile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=15)),
                ('language', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'profile_page_userprofile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.CharField()),
                ('last_updated_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.BigIntegerField(blank=True, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.BigIntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=15)),
                ('login_id', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('last_updated_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.BigIntegerField(blank=True, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_profile',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='createpitch',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='daftar',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='PitchVideo',
        ),
    ]
