# Generated by Django 5.0.7 on 2024-07-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_daftardetail_pitchvideos_profilepageuserprofile_and_more'),
    ]

    operations = [
    ]
