# Generated by Django 5.0.7 on 2024-07-30 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20240730_1719'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='createpitch',
            table='create_pitch',
        ),
        migrations.AlterModelTable(
            name='daftar',
            table='daftar',
        ),
    ]
