# Generated by Django 5.0.7 on 2024-07-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='dateofbirth',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='phoneno',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_id',
            field=models.EmailField(default='example@example.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(max_length=20),
        ),
    ]
