# Generated by Django 5.0.7 on 2024-07-29 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0002_rename_dateofbirth_userprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'managed': False},
        ),
    ]
