# Generated by Django 5.0.7 on 2024-07-30 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0004_userdetail_alter_userprofile_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
