# Generated by Django 5.0.7 on 2024-08-07 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0005_delete_userdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
    ]
